// Национальный сертификат — 01.12.2024, 2-вариант.
// 45 заданий: 1–32 single_choice, 33–35 matching, 36–45 open_ended.
// Условия переведены на русский по оригинальному варианту; ключи взяты из листа ответов.
var questions = [
  {
    id: 1,
    type: "single_choice",
    question: "Сколько цифр содержит число $8\\cdot40^{45}\\cdot36^2\\cdot625^{25}\\cdot216$?",
    options: ["149", "148", "147", "150"],
    correctAnswer: 0,
  },
  {
    id: 2,
    type: "single_choice",
    question: "Вычислите $\\frac1{30}+\\frac1{60}+\\frac1{100}+\\frac1{150}+\\frac1{210}$.",
    options: ["$1/15$", "$1/14$", "$2/19$", "$1/90$"],
    correctAnswer: 1,
  },
  {
    id: 3,
    type: "single_choice",
    question: "Из городов $A$ и $B$ два туриста отправились в город $C$. Если туристы из $A$ и $B$ идут навстречу друг другу, они встречаются через $t_1$. До города $C$ они одновременно доходят за $t_2$. Найдите произведение их скоростей.",
    options: ["$\\frac{S^2}{2}(\\frac1{t_1}+\\frac1{t_2})$", "$\\frac{S^2}{2}(\\frac1{t_1}-\\frac1{t_2})$", "$\\frac{S^2}{2}(\\frac1{t_1^2}-\\frac1{t_2^2})$", "$\\frac{S^2}{4}(\\frac1{t_1^2}-\\frac1{t_2^2})$"],
    correctAnswer: 3,
  },
  {
    id: 4,
    type: "single_choice",
    question: "Месячная зарплата семьи — 15 000 000 сум. 60% тратится на семейные расходы, а 30% оставшихся денег семья кладёт в банк. Сколько сумов она откладывает?",
    options: ["1 800 000", "2 000 000", "2 500 000", "2 200 000"],
    correctAnswer: 0,
  },
  {
    id: 5,
    type: "single_choice",
    question: "Если $a\\cdot b=3^4\\cdot5^2\\cdot7^3\\cdot11$, найдите наибольшее возможное значение $\\operatorname{НОД}(a;b)$.",
    options: ["105", "315", "735", "1025"],
    correctAnswer: 1,
  },
  {
    id: 6,
    type: "single_choice",
    question: "Вычислите $\\tan\\frac{\\pi}{4}+\\sqrt3\\sin\\frac{7\\pi}{3}$.",
    options: ["1", "1,5", "2", "2,5"],
    correctAnswer: 3,
  },
  {
    id: 7,
    type: "single_choice",
    question: "В убывающей арифметической прогрессии $a_1+a_3+a_5=15$ и $a_2^2+a_3^2+a_4^2=83$. Найдите $a_{13}$.",
    options: ["25", "-17", "-15", "15"],
    correctAnswer: 2,
  },
  {
    id: 8,
    type: "single_choice",
    question: "Вычислите $\\sqrt[3]{54+30\\sqrt3}+\\sqrt[3]{54-30\\sqrt3}$.",
    options: ["3", "9", "6", "18"],
    correctAnswer: 2,
  },
  {
    id: 9,
    type: "single_choice",
    question: "Сколько действительных корней имеет уравнение $|x+2|+|x+5|=9+|x-4|$?",
    options: ["1", "2", "3", "Действительных решений нет"],
    correctAnswer: 1,
  },
  {
    id: 10,
    type: "single_choice",
    question: "В геометрической прогрессии из 6 членов сумма первых трёх равна 26, а последних трёх — 702. Найдите знаменатель прогрессии.",
    options: ["8", "6", "2", "3"],
    correctAnswer: 3,
  },
  {
    id: 11,
    type: "single_choice",
    question: "При каких значениях $a$ уравнение $\\sqrt{25-x^2}=a$ имеет действительные корни?",
    options: ["$[0;5]$", "$[0;25]$", "$(0;25)$", "$(0;5)$"],
    correctAnswer: 0,
  },
  {
    id: 12,
    type: "single_choice",
    question: "Если $7^a=6$ и $6^b=12$, выразите $\\log_{81}(98\\sqrt3)$ через $a$ и $b$.",
    options: ["$\\frac{4+ab}{16a-8ab}$", "$\\frac{4+ab}{16a+8ab}$", "$\\frac{4-ab}{16a+8ab}$", "$\\frac{4-ab}{16a-8ab}$"],
    correctAnswer: 0,
  },
  {
    id: 13,
    type: "single_choice",
    question: "Сколько решений имеет уравнение $2\\sin^2(x-\\pi/3)-5\\sin(x-\\pi/3)+2=0$ на $[-\\pi;2\\pi]$?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
  },
  {
    id: 14,
    type: "single_choice",
    question: "Решите неравенство $\\frac{3^{x-3x-2}}{3^{x-2x}}>1+(\\frac23)^x$.",
    options: ["$(-\\infty;0)$", "$(0;\\log_{2/3}(1/3))$", "$(-1;\\log_{2/3}(1/3))$", "$(-\\infty;0)\\cup(0;\\log_{2/3}(1/3))$"],
    correctAnswer: 1,
  },
  {
    id: 15,
    type: "single_choice",
    question: "Найдите произведение действительных корней уравнения $\\lg^2(x+1)=\\lg(x-1)\\lg(x+1)+2\\lg^2(x-1)$.",
    options: ["2", "$3\\sqrt2$", "1", "$\\sqrt2$"],
    correctAnswer: 1,
  },
  {
    id: 16,
    type: "single_choice",
    question: "Вычислите $\\frac1{2\\sqrt6+5}-5+2\\sqrt6$.",
    options: ["$4\\sqrt6$", "10", "0", "$3\\sqrt6$"],
    correctAnswer: 2,
  },
  {
    id: 17,
    type: "single_choice",
    question: "Решите неравенство $-5\\sqrt[4]{x}+\\sqrt{x}+6\\ge0$.",
    options: ["$[0;16]$", "$[0;16]\\cup[81;\\infty)$", "$[16;81]$", "Действительных решений нет"],
    correctAnswer: 1,
  },
  {
    id: 18,
    type: "single_choice",
    question: "Упростите $\\left(\\frac{8a^3+b^3}{4a^2-b^2}+b\\right):\\frac{a^2}{2a-b}$.",
    options: ["1", "$2a-b$", "4", "$2a+b$"],
    correctAnswer: 2,
  },
  {
    id: 19,
    type: "single_choice",
    question: "Найдите сумму целых решений неравенства $\\left(2x+1-\\frac6x\\right)\\left(\\frac{28}{x}-7+(\\sqrt{-3-2x})^2\\right)\\ge0$.",
    options: ["-22", "-25", "-27", "-28"],
    correctAnswer: 2,
  },
  {
    id: 20,
    type: "single_choice",
    question: "Найдите наименьшее целое значение функции $y=x^2-\\sqrt{9+x^2}$.",
    options: ["-4", "-2", "-1", "-3"],
    correctAnswer: 3,
  },
  {
    id: 21,
    type: "single_choice",
    question: "Если $h(x)=kx+l$ и $f(x)=mx+n$, найдите $\\frac{k+l}{m+n}$ по условию и графику исходного варианта.",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
  },
  {
    id: 22,
    type: "single_choice",
    question: "Если $f(x)=3^x\\log_3(3x)$, найдите $f'(1)$.",
    options: ["$\\frac{\\ln^2 3+1}{\\ln3}$", "$\\frac{3\\ln^2 3+3}{\\ln3}$", "$\\frac{3\\ln^2 3-3}{\\ln3}$", "$\\frac{3\\ln^2 3+1}{\\ln3}$"],
    correctAnswer: 1,
  },
  {
    id: 23,
    type: "single_choice",
    question: "Найдите площадь областей, ограниченных функциями $f(x)=|x^2+3x+2|$ и $g(x)=x+2$.",
    options: ["$1/2$", "$1/3$", "1", "2"],
    correctAnswer: 2,
  },
  {
    id: 24,
    type: "single_choice",
    question: "На рисунке окружность с центром $O$ пересекает квадрат $ABCD$ в точках $K$ и $L$. Дано $OD=4$, $DL=2$, $BC=6$. Найдите длину малой дуги $KL$.",
    options: ["$\\sqrt3\\pi$", "$2\\pi$", "$\\sqrt5\\pi$", "$\\sqrt6\\pi$"],
    correctAnswer: 2,
  },
  {
    id: 25,
    type: "single_choice",
    question: "В треугольнике $ABC$ $AB=5$, $BC=4$, $AC=3$. Из вершины $C$ к стороне $AB$ проведены высота и биссектриса. Найдите расстояние между ними.",
    options: ["$13/35$", "$11/35$", "$17/35$", "$12/35$"],
    correctAnswer: 3,
  },
  {
    id: 26,
    type: "single_choice",
    question: "В прямоугольном треугольнике $ABC$ окружность касается катета $AB$ и проходит через противоположную вершину. Центр $O$ лежит на гипотенузе $BC$, а окружность пересекает гипотенузу в $E$. Если $BE=1$, $OC=4$ и $\\angle BCD=\\angle ACD$, найдите расстояние от $O$ до $DC$.",
    options: ["$2\\sqrt{10}/5$", "$3\\sqrt{10}/5$", "$4\\sqrt{10}/5$", "$\\sqrt{10}/5$"],
    correctAnswer: 0,
  },
  {
    id: 27,
    type: "single_choice",
    question: "В прямоугольной трапеции меньшая основа равна большему боковому боку, высота равна 4, большая диагональ равна $4\\sqrt5$. Найдите площадь трапеции.",
    options: ["32", "35", "26", "24"],
    correctAnswer: 2,
  },
  {
    id: 28,
    type: "single_choice",
    question: "Через точку $A$, не лежащую в плоскости, проведены высота $AH$ и наклонная $AM$. Угол между наклонной и плоскостью равен 37°, $AH=6$. Найдите кратчайшее расстояние от $H$ до $AM$. Считать $\\cos37^\\circ=0,8$.",
    options: ["1,8", "3,6", "4,8", "2,4"],
    correctAnswer: 2,
  },
  {
    id: 29,
    type: "single_choice",
    question: "Площадь треугольника $ABC$ равна 60. Если $\\vec{BE}=-\\frac12\\vec{BA}$, найдите площадь треугольника $ACE$.",
    options: ["30", "60", "90", "120"],
    correctAnswer: 2,
  },
  {
    id: 30,
    type: "single_choice",
    question: "У правильного многоугольника число сторон $n$ — чётное. Угол между наибольшей и наименьшей диагоналями, выходящими из одной вершины, равен 45°. Найдите сумму внутренних углов.",
    options: ["1080°", "1440°", "720°", "1800°"],
    correctAnswer: 0,
  },
  {
    id: 31,
    type: "single_choice",
    question: "Найдите количество пустых множеств среди следующих четырёх множеств: $x^2-\\sqrt{10}+\\pi=0$ на $R$; $x^2+1=0$ на $R$; $|x|=-3$ на $R$; $x^2+3x+2=0$ на множестве иррациональных чисел.",
    options: ["1", "2", "3", "4"],
    correctAnswer: 2,
  },
  {
    id: 32,
    type: "single_choice",
    question: "Из четырёхзначных чисел, состоящих только из нечётных цифр, выбирают число, кратное 5. Найдите вероятность.",
    options: ["$1/72$", "$1/36$", "$1/108$", "$1/5$"],
    correctAnswer: 0,
  },
  {
    id: 33,
    type: "matching",
    context: "Точки $O(0;0;0)$, $A(0;0;3)$ и $B(\\sqrt2;\\sqrt2;0)$; точки $D$ и $C$ лежат соответственно на осях $OX$ и $OY$. Отрезок $OB$ является высотой и медианой треугольника $OCD$. Сопоставьте задания 33–35 с вариантами A–F. Считать $\\pi\\approx3$.",
    optionsPool: { A: "3", B: "4", C: "6", D: "12", E: "16", F: "24" },
    items: [{ id: 33, text: "Найдите объём пирамиды $AOCD$.", correctAnswer: "B" }],
  },
  {
    id: 34,
    type: "matching",
    context: "Точки $O(0;0;0)$, $A(0;0;3)$ и $B(\\sqrt2;\\sqrt2;0)$; точки $D$ и $C$ лежат соответственно на осях $OX$ и $OY$.",
    optionsPool: { A: "3", B: "4", C: "6", D: "12", E: "16", F: "24" },
    items: [{ id: 34, text: "Найдите объём тела, полученного вращением треугольника $AOB$ вокруг стороны $AO$ на 360°.", correctAnswer: "E" }],
  },
  {
    id: 35,
    type: "matching",
    context: "Точки $O(0;0;0)$, $A(0;0;3)$ и $B(\\sqrt2;\\sqrt2;0)$; точки $D$ и $C$ лежат соответственно на осях $OX$ и $OY$.",
    optionsPool: { A: "3", B: "4", C: "6", D: "12", E: "16", F: "24" },
    items: [{ id: 35, text: "Найдите объём тела, полученного вращением треугольника $OCD$ вокруг стороны $CD$ на 360°.", correctAnswer: "D" }],
  },
  {
    id: 36,
    type: "open_ended",
    question: "$a,b,c$ — действительные корни уравнения $x^3-9x^2+11x-1=0$. Пусть $t=\\sqrt a+\\sqrt b+\\sqrt c$.",
    subQuestions: [
      { id: "a", text: "а) Найдите $a+b+c+abc+ab+bc+ac$.", correctAnswer: "21" },
      { id: "b", text: "б) Вычислите $t^4-18t^2-8t$.", correctAnswer: "-37" },
    ],
  },
  {
    id: 37,
    type: "open_ended",
    question: "Дано уравнение $\\sqrt{7+8\\cos^2(\\pi x/18)}=4\\sin^2(\\pi x/18)$.",
    subQuestions: [
      { id: "a", text: "а) Найдите сумму решений на $[0;18]$.", correctAnswer: "18" },
      { id: "b", text: "б) Найдите количество корней на $[20;30]$.", correctAnswer: "2" },
    ],
  },
  {
    id: 38,
    type: "open_ended",
    question: "Пусть $f(x)=\\frac{x+3}{x-1}$. Рассматривается обратная функция к $f^{-1}(x)-f(x)$.",
    subQuestions: [
      { id: "a", text: "а) Найдите $f^{-1}(2)$.", correctAnswer: "5" },
      { id: "b", text: "б) Сколько целых чисел не могут быть корнями уравнения $f(x)=f^{-1}(x)$?", correctAnswer: "1" },
    ],
  },
  {
    id: 39,
    type: "open_ended",
    question: "Внутри прямоугольной трапеции построен прямоугольник максимальной площади; одна его сторона лежит на большей основе. Основы трапеции равны 6 и 16, высота — 15.",
    subQuestions: [
      { id: "a", text: "а) Найдите площадь прямоугольника.", correctAnswer: "96" },
      { id: "b", text: "б) Найдите модуль разности площадей трапеции и прямоугольника.", correctAnswer: "69" },
    ],
  },
  {
    id: 40,
    type: "open_ended",
    question: "Для функции $f(x)$ выполнено $f''(x)=12x^2+6x$, $f'(1)=9$, $f(1)=5$.",
    subQuestions: [
      { id: "a", text: "а) Найдите $f(0)$.", correctAnswer: "1" },
      { id: "b", text: "б) Если $f(2024)=2$ и $f(2023)=3$, вычислите $\\int_{2023}^{2024}(f(x)+xf'(x))\\,dx$.", correctAnswer: "-2021" },
    ],
  },
  {
    id: 41,
    type: "open_ended",
    question: "На рисунке квадрат $ABCD$ и окружность с центром в $B$ и радиусом $r$.",
    subQuestions: [
      { id: "a", text: "а) Найдите отношение площади закрашенной части квадрата к площади незакрашенной части.", correctAnswer: "3" },
      { id: "b", text: "б) Если $r=2$, найдите площадь закрашенной части.", correctAnswer: "$2\\sqrt2+3$" },
    ],
  },
  {
    id: 42,
    type: "open_ended",
    question: "В прямоугольном треугольнике $ABC$ на катетах $AC$ и $BC$ выбраны точки $D$ и $E$ так, что $AD=BC$ и $CD=BE$.",
    subQuestions: [
      { id: "a", text: "а) Найдите угол $AOD$.", correctAnswer: "45°" },
      { id: "b", text: "б) Если $BC=10$ и $AE=2\\sqrt{58}$, найдите $S_{ABC}$.", correctAnswer: "70" },
    ],
  },
  {
    id: 43,
    type: "open_ended",
    question: "В параллелограмме $ABCD$ на диагоналях выбраны точки $A_1,B_1,C_1,D_1,E$, причём $A_1E\\parallel AD$, $C_1E\\parallel CD$, $AC:A_1C_1=5:3$, $BD:B_1D_1=3:2$.",
    subQuestions: [
      { id: "a", text: "а) Найдите $S_{A_1C_1E}/S_{ACD}$.", correctAnswer: "9/50" },
      { id: "b", text: "б) Найдите $S_{A_1B_1C_1D_1}/S_{ABCD}$.", correctAnswer: "2/5" },
    ],
  },
  {
    id: 44,
    type: "open_ended",
    question: "В шар вписан конус, объём которого составляет $1/4$ объёма шара. Считать $\\pi\\approx3$.",
    subQuestions: [
      { id: "a", text: "а) Если $H_{конуса}=(\\sqrt2+\\sqrt5)/3$ и $H_{конуса}>R_{шара}$, найдите объём шара.", correctAnswer: "4" },
      { id: "b", text: "б) Если $R_{шара}=H_{конуса}=\\sqrt3+2\\sqrt2$, найдите площадь поверхности сферы, вписанной в конус.", correctAnswer: "12" },
    ],
  },
  {
    id: 45,
    type: "open_ended",
    question: "Каркас цирка имеет форму параболы: высота от земли до самой высокой точки равна 8, ширина — 20. На высоте 6 к каркасу прикреплён трос, идущий к земле.",
    subQuestions: [
      { id: "a", text: "а) Найдите $\\tan\\alpha$.", correctAnswer: "0,8" },
      { id: "b", text: "б) Найдите $OD$.", correctAnswer: "2,5" },
    ],
  },
];
