// Национальный сертификат — 01.12.2024, 1-вариант.
// 45 заданий: 1–32 single_choice, 33–35 matching, 36–45 open_ended.
// Условия переведены на русский по оригинальному варианту; ключи взяты из листа ответов.
var questions = [
  {
    id: 1,
    type: "single_choice",
    question: "Среди шестизначных чисел вида $2023ab$ сколько чисел делятся на 36 без остатка?",
    options: ["3", "2", "1", "Таких нет"],
    correctAnswer: 0,
  },
  {
    id: 2,
    type: "single_choice",
    question: "Вычислите $4,(36):3,1(9)+\\frac{1}{3}\\frac{1}{7}$.",
    options: ["$35/22$", "$1\\frac{15}{22}$", "$17/35$", "$2\\frac{5}{22}$"],
    correctAnswer: 1,
  },
  {
    id: 3,
    type: "single_choice",
    question: "Корабль по течению проходит расстояние $S$ за 80 минут, а против течения половину расстояния $S$ — за 60 минут. Во сколько раз скорость корабля больше скорости течения?",
    options: ["6", "7", "4", "5"],
    correctAnswer: 3,
  },
  {
    id: 4,
    type: "single_choice",
    question: "Месячная зарплата семьи — 15 000 000 сум. 60% тратится на семейные расходы, а 30% оставшихся денег семья кладёт в банк. Сколько сумов она откладывает?",
    options: ["1 800 000", "2 000 000", "2 500 000", "2 200 000"],
    correctAnswer: 0,
  },
  {
    id: 5,
    type: "single_choice",
    question: "Если $x+y=10^z$, $x^2+y^2=10^{z+1}$ и $x^3+y^3=a\\cdot10^{3z}+b\\cdot10^{2z}$, найдите сумму рациональных значений $a$ и $b$.",
    options: ["15,5", "16,5", "18,5", "14,5"],
    correctAnswer: 3,
  },
  {
    id: 6,
    type: "single_choice",
    question: "Вычислите $\\frac{1}{2\\sqrt6+5}-5+2\\sqrt6$.",
    options: ["$4\\sqrt6$", "10", "0", "$3\\sqrt6$"],
    correctAnswer: 2,
  },
  {
    id: 7,
    type: "single_choice",
    question: "Вычислите $\\sqrt{21-12\\sqrt3}\\cdot\\sqrt{(\\sqrt3-4)^2}$.",
    options: ["$11\\sqrt3-18$", "$14\\sqrt3-17$", "$15+7\\sqrt3$", "$18-11\\sqrt3$"],
    correctAnswer: 0,
  },
  {
    id: 8,
    type: "single_choice",
    question: "В арифметической прогрессии $a_1+a_3+a_5+\\dots+a_{2n-1}=96$ и $a_{n-2}+a_{n+2}=12$. Найдите $n$.",
    options: ["8", "32", "24", "16"],
    correctAnswer: 3,
  },
  {
    id: 9,
    type: "single_choice",
    question: "Сумма бесконечной убывающей геометрической прогрессии равна 22,5, сумма первых двух членов — 20, $0<q<1$. Найдите четвёртый член прогрессии.",
    options: ["$5/18$", "$1$", "$5/3$", "$5/9$"],
    correctAnswer: 3,
  },
  {
    id: 10,
    type: "single_choice",
    question: "Если $a=2024$ и $b=2023$, найдите $a^3-b^3+a^2+b^2+2-5ab$.",
    options: ["4", "1", "-1", "0"],
    correctAnswer: 0,
  },
  {
    id: 11,
    type: "single_choice",
    question: "Если $x+y=3$ и $xy=-1$, вычислите $\\frac{x(y+1)^2-y(x+1)^2}{x^2(y+1)-y^2(x+1)}$.",
    options: ["-1", "0", "1", "10"],
    correctAnswer: 2,
  },
  {
    id: 12,
    type: "single_choice",
    question: "Представьте $12345''$ в градусах, минутах и секундах.",
    options: ["$3^\\circ25'45''$", "$3^\\circ45'55''$", "$4^\\circ25'45''$", "$4^\\circ26'45''$"],
    correctAnswer: 0,
  },
  {
    id: 13,
    type: "single_choice",
    question: "Упростите выражение из задания 13: $\\frac{4\\sin^2a-\\cos4a-2\\sin2a\\cos2a}{1-\\cos24a\\sin24a-\\cos44a}$.",
    options: ["$1/(8\\cos^2a)$", "$1/(2\\cos^2a)$", "1", "$-1/\\cos2a$"],
    correctAnswer: 0,
  },
  {
    id: 14,
    type: "single_choice",
    question: "Сколько действительных корней имеет уравнение $16^{1/x}-20\\cdot2^{2/x-2}+4=0$?",
    options: ["3", "1", "2", "3"],
    correctAnswer: 1,
  },
  {
    id: 15,
    type: "single_choice",
    question: "Найдите произведение действительных корней уравнения $\\sqrt{\\log_2\\sqrt{4^x}}=-\\frac1{\\log_4x}$. Если корень один, укажите его.",
    options: ["$1/16$", "$1/4$", "$1/2$", "2"],
    correctAnswer: 0,
  },
  {
    id: 16,
    type: "single_choice",
    question: "Найдите произведение действительных корней уравнения $|3x+6|=15$. Если корень один, укажите его.",
    options: ["-21", "-7", "-5", "0"],
    correctAnswer: 0,
  },
  {
    id: 17,
    type: "single_choice",
    question: "Найдите сумму действительных корней уравнения $\\frac{x^2+4}{x+2\\sqrt{x}+2}=\\frac{x^2-5x+4}{x+3\\sqrt{x}+2}$. Если корень один, укажите его.",
    options: ["1", "0", "-1", "Решений нет"],
    correctAnswer: 1,
  },
  {
    id: 18,
    type: "single_choice",
    question: "Найдите сумму всех целых чисел, удовлетворяющих неравенству $2\\sqrt{x-3}>x-6$.",
    options: ["56", "63", "74", "81"],
    correctAnswer: 1,
  },
  {
    id: 19,
    type: "single_choice",
    question: "Сколько целых чисел удовлетворяют неравенству $\\sqrt{x^2-6x+9}\\cdot\\sqrt{-x^2+3x+10}>0$?",
    options: ["5", "6", "Бесконечно много", "8"],
    correctAnswer: 0,
  },
  {
    id: 20,
    type: "single_choice",
    question: "Сколько целых чисел принадлежит области определения функции $f(x)=\\frac{\\sqrt{-x^2+3x+10}}{|1-\\log_x2|(\\sin x-\\pi/3)}$?",
    options: ["5", "6", "7", "3"],
    correctAnswer: 3,
  },
  {
    id: 21,
    type: "single_choice",
    question: "Найдите неопределённый интеграл $\\int\\frac{\\ln\\ln x}{x}\\,dx$.",
    options: ["$\\ln x(\\ln\\ln x-1)+C$", "$\\ln x(\\ln\\ln x+1)+C$", "$\\ln\\ln x+C$", "$\\ln x+C$"],
    correctAnswer: 0,
  },
  {
    id: 22,
    type: "single_choice",
    question: "Если $f(x)=\\sin^3(x/2)$, найдите $f'(2\\pi/3)$.",
    options: ["$9/16$", "$9/8$", "$7/15$", "$7/5$"],
    correctAnswer: 0,
  },
  {
    id: 23,
    type: "single_choice",
    question: "В четырёхугольник $ABCD$ вписана окружность. $AB=CD=7$, $AD=6$. Найдите $BC$.",
    options: ["6", "8", "14", "15"],
    correctAnswer: 1,
  },
  {
    id: 24,
    type: "single_choice",
    question: "В равнобедренный треугольник $ABC$ вписана окружность, $AB=AC$. Точка касания делит $AB$ на отрезки 6 и 4, причём $AB>BC$. Найдите площадь треугольника $ABC$.",
    options: ["96", "$10\\sqrt{21}$", "48", "$8\\sqrt{21}$"],
    correctAnswer: 3,
  },
  {
    id: 25,
    type: "single_choice",
    question: "По рисунку найдите кратчайшее расстояние от точки A до точки B.",
    options: ["25", "15", "10", "$10\\sqrt2$"],
    correctAnswer: 0,
  },
  {
    id: 26,
    type: "single_choice",
    question: "В параллелограмме $ABCD$ на стороне $BC$ взята точка $E$, а на $AD$ — точка $F$. Отрезки $EF$ и $AC$ пересекаются в $P$. $AD=4AF$, $AC=3AP$. Если площадь четырёхугольника $ABEP$ равна 16, найдите площадь заштрихованной области.",
    options: ["22", "21", "20", "23"],
    correctAnswer: 0,
  },
  {
    id: 27,
    type: "single_choice",
    question: "Найдите наименьшее целое значение функции $y=x^2-\\sqrt{9+x^2}$.",
    options: ["-3", "1", "0", "3"],
    correctAnswer: 0,
  },
  {
    id: 28,
    type: "single_choice",
    question: "Даны правильный восьмиугольник $ABCDEFGHI$ и правильный пятиугольник $AGJKI$. Найдите угол $BAG$.",
    options: ["27°", "36°", "54°", "20°"],
    correctAnswer: 0,
  },
  {
    id: 29,
    type: "single_choice",
    question: "В прямоугольнике $ABCD$ вершина $A$ находится в начале координат, $B$ — на оси $Ox$, $C=(5;4)$, а $\\frac12\\vec{BE}=\\vec{BC}$. Найдите площадь четырёхугольника $ABED$.",
    options: ["20", "15", "30", "40"],
    correctAnswer: 2,
  },
  {
    id: 30,
    type: "single_choice",
    question: "Через точку $A$, не лежащую в плоскости, проведены высота $AH$ и наклонная $AM$. Угол между наклонной и плоскостью равен 37°, $AH=6$. Найдите кратчайшее расстояние от $H$ до наклонной $AM$. Считать $\\cos37^\\circ=0,8$.",
    options: ["1,8", "3,6", "4,8", "2,4"],
    correctAnswer: 2,
  },
  {
    id: 31,
    type: "single_choice",
    question: "Даны множества целых чисел $A=[-3;5)$, $B=[-5;3)$, $C=[-4;6)$, $D=[-3;7)$. Найдите число подмножеств множества $(A\\cup C)'\\cap(B\\cup D)$.",
    options: ["2", "16", "8", "4"],
    correctAnswer: 3,
  },
  {
    id: 32,
    type: "single_choice",
    question: "Из четырёхзначных чисел, состоящих только из нечётных цифр, выбирают число, кратное 5. Найдите вероятность.",
    options: ["$1/72$", "$1/36$", "$1/108$", "$1/5$"],
    correctAnswer: 0,
  },
  {
    id: 33,
    type: "matching",
    context: "Даны два одинаковых цилиндра диаметром 10 см. Из цилиндров вырезана деталь в форме колена. Сопоставьте задания 33–35 с вариантами A–F. Считать $\\pi\\approx3$.",
    optionsPool: {
      A: "1200",
      B: "900",
      C: "$30\\sqrt2$",
      D: "$10\\sqrt{13}$",
      E: "2250",
      F: "3000",
    },
    items: [{ id: 33, text: "Найдите площадь боковой поверхности получившегося тела (см²).", correctAnswer: "B" }],
  },
  {
    id: 34,
    type: "matching",
    context: "Даны два одинаковых цилиндра диаметром 10 см. Из цилиндров вырезана деталь в форме колена.",
    optionsPool: {
      A: "1200",
      B: "900",
      C: "$30\\sqrt2$",
      D: "$10\\sqrt{13}$",
      E: "2250",
      F: "3000",
    },
    items: [{ id: 34, text: "Найдите объём получившегося тела (см³).", correctAnswer: "E" }],
  },
  {
    id: 35,
    type: "matching",
    context: "Даны два одинаковых цилиндра диаметром 10 см. Из цилиндров вырезана деталь в форме колена.",
    optionsPool: {
      A: "1200",
      B: "900",
      C: "$30\\sqrt2$",
      D: "$10\\sqrt{13}$",
      E: "2250",
      F: "3000",
    },
    items: [{ id: 35, text: "Найдите длину сечения (см).", correctAnswer: "D" }],
  },
  {
    id: 36,
    type: "open_ended",
    question: "Решите систему $\\begin{cases}x^2-3x+9=5y^2+y-13,\\\\y^2-3y+2=xy-3y-2x+6.\\end{cases}$",
    subQuestions: [
      { id: "a", text: "а) Сколько пар $(x;y)$ удовлетворяют системе?", correctAnswer: "4" },
      { id: "b", text: "б) Если решения — $(x_1;y_1),\\dots,(x_n;y_n)$, найдите $x_1+\\dots+x_n$.", correctAnswer: "7" },
    ],
  },
  {
    id: 37,
    type: "open_ended",
    question: "$2\\cos^2 3x-(4a^2-7)\\cos3x+2a^2-4=0$.",
    subQuestions: [
      { id: "a", text: "а) В интервале $[-\\pi/2;\\pi/2]$ какое минимальное число корней может иметь уравнение?", correctAnswer: "4" },
      { id: "b", text: "б) Найдите наименьшее натуральное $a$, при котором на $[-\\pi/3;\\pi/2]$ уравнение имеет 3 корня.", correctAnswer: "1" },
    ],
  },
  {
    id: 38,
    type: "open_ended",
    question: "$f(x)=ax^2+bx+c$ — квадратная функция. Вершина параболы $(1;4)$, пересечения с осью $Ox$ — $(-2;0)$ и $(k;0)$.",
    subQuestions: [
      { id: "a", text: "а) Найдите $\\frac{a+b+c}{k}$.", correctAnswer: "1" },
      { id: "b", text: "б) Если $g(x)=3f(x/5)-2$, найдите сумму координат вершины параболы $g$.", correctAnswer: "15" },
    ],
  },
  {
    id: 39,
    type: "open_ended",
    question: "На интервале $(-9;3)$ дан график производной $f'(x)$.",
    subQuestions: [
      { id: "a", text: "а) В какой точке интервала $(-5;3)$ функция $f(x)$ достигает максимума?", correctAnswer: "-3" },
      { id: "b", text: "б) В какой точке интервала $(-9;-3)$ функция $f(x)$ достигает минимума?", correctAnswer: "-5" },
    ],
  },
  {
    id: 40,
    type: "open_ended",
    question: "Функции $y_1=\\sqrt{x-1}+2$ и $y_2=(x+3)/2$ пересекаются в точках $A$ и $B$.",
    subQuestions: [
      { id: "a", text: "а) Найдите расстояние между $A$ и $B$.", correctAnswer: "2√5" },
      { id: "b", text: "б) Найдите площадь области, образованной пересечением графиков $y_1$ и $y_2$.", correctAnswer: "4/3" },
    ],
  },
  {
    id: 41,
    type: "open_ended",
    question: "В прямоугольном треугольнике $ABC$ задано $\\angle BDF=135^\\circ$, $BD=\\sqrt2$, $FE=2EC=2$, $AF=3$.",
    subQuestions: [
      { id: "a", text: "а) Найдите гипотенузу $BC$.", correctAnswer: "5√2" },
      { id: "b", text: "б) Найдите сумму площадей заштрихованных областей.", correctAnswer: "5" },
    ],
  },
  {
    id: 42,
    type: "open_ended",
    question: "У параллелограмма $ABCD$ тупой угол равен $120^\\circ$, периметр равен 26. В треугольник $ABD$ вписана окружность радиуса $\\sqrt3$.",
    subQuestions: [
      { id: "a", text: "а) Найдите площадь параллелограмма.", correctAnswer: "20√3" },
      { id: "b", text: "б) Найдите большую сторону параллелограмма.", correctAnswer: "8" },
    ],
  },
  {
    id: 43,
    type: "open_ended",
    question: "Дан правильный двенадцатиугольник со стороной $\\sqrt3-1$.",
    subQuestions: [
      { id: "a", text: "а) По рисунку найдите длину $LC$.", correctAnswer: "2" },
      { id: "b", text: "б) Найдите площадь заштрихованной области $LEF$.", correctAnswer: "1" },
    ],
  },
  {
    id: 44,
    type: "open_ended",
    question: "Дана полуокружность радиуса $R$, из которой изготовлен конус.",
    subQuestions: [
      { id: "a", text: "а) Найдите синус угла между образующей конуса и его осью.", correctAnswer: "1/2" },
      { id: "b", text: "б) Если $R=2\\sqrt3$, найдите площадь поверхности сферы, вписанной в конус. Считать $\\pi\\approx3$.", correctAnswer: "12" },
    ],
  },
  {
    id: 45,
    type: "open_ended",
    question: "Для движения корабль расходует деньги на работников и топливо. Работникам платят 250 долларов в час, на топливо расходуется $v/3$ долларов в час, где $v$ — средняя скорость корабля (км/ч).",
    subQuestions: [
      { id: "a", text: "а) Если затраты на прохождение 10 км минимальны, найдите $v$.", correctAnswer: "5" },
      { id: "b", text: "б) Найдите минимальные затраты на прохождение 10 км.", correctAnswer: "750" },
    ],
  },
];
